project:
  name: HD_landuse
  workspace: /home/chad/Desktop/folder/ohsome2label/example_result_roads_test
  project_time: 2024-03-14
  task: segmentation

osm:
  api: ohsome
  url: https://api.ohsome.org/v1/elements/geometry
  bboxes: [-73.70164,45.47775,-73.6379,45.50655]
  tags:
    - {'label': 'motorway', 'key': 'highway', 'value': 'motorway'}
    - {'label': 'secondary', 'key': 'highway', 'value': 'secondary'}
    - {'label': 'tertiary', 'key': 'highway', 'value': 'tertiary'}
    #- {'label': 'secondary_link', 'key': 'highway', 'value': 'secondary_link'}
    #- {'label': 'tertiary_link', 'key': 'highway', 'value': 'tertiary_link'}
    #- {'label': 'service', 'key': 'highway', 'value': 'service'}
    #- {'label': 'primary', 'key': 'highway', 'value': 'primary'}

    #- {'label': 'residential', 'key': 'highway', 'value': 'residential'}

  timestamp: 2023-01-01
  types: line

image:
  img_api: bing
  img_url: http://t0.tiles.virtualearth.net/tiles/a{q}.png?g=854&mkt=en-US&token={token}
  api_token : AodB7xAjjC4O-Q7bf7pCTZA6fjvLXGeiYQQ1nn3zljjdTfmggIQiJDT-YWzWtN9Z
  zoom: 17 